// Generated by IcedCoffeeScript 1.3.3g
(function() {
  var colors, exec, fs, iced, star, watch, _, __iced_k, __iced_k_noop,
    __slice = [].slice;

  iced = {
    Deferrals: (function() {

      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) return this.continuation(this.ret);
      };

      _Class.prototype.defer = function(defer_params) {
        var _this = this;
        ++this.count;
        return function() {
          var inner_params, _ref;
          inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          if (defer_params != null) {
            if ((_ref = defer_params.assign_fn) != null) {
              _ref.apply(null, inner_params);
            }
          }
          return _this._fulfill();
        };
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  __iced_k = __iced_k_noop = function() {};

  watch = require('watch');

  fs = require('fs');

  exec = require('child_process').exec;

  _ = require('underscore');

  colors = require('colors');

  star = '\u2606'.red;

  module.exports.init = require('./init');

  module.exports.serve = require('./serve');

  module.exports.build = require('./build');

  module.exports.clean = function(callback) {
    var ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "src/index.iced",
        funcname: "clean"
      });
      exec('rm -rf release/', __iced_deferrals.defer({
        lineno: 12
      }));
      __iced_deferrals._fulfill();
    })(function() {
      console.log("Removed release directory");
      return typeof callback === "function" ? callback() : void 0;
    });
  };

  module.exports.open = function(port) {
    var err, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "src/index.iced",
        funcname: "open"
      });
      exec("open http://localhost:" + port, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return err = arguments[0];
          };
        })(),
        lineno: 17
      }));
      __iced_deferrals._fulfill();
    })(function() {
      if (typeof err !== "undefined" && err !== null) return console.error(err);
    });
  };

  module.exports.watch = function(callback) {
    var buildWrapper, dir, dirs, fileChangeCallback, lazyBuild, opts, _i, _len;
    buildWrapper = function() {
      process.stdout.write("" + star + " ");
      return module.exports.build();
    };
    lazyBuild = _.debounce(buildWrapper, 500);
    fileChangeCallback = function(f, curr, prev) {
      if (!curr && !prev) return;
      return lazyBuild();
    };
    opts = {
      ignoreDotFiles: true,
      filter: function(f) {
        return !(f.match(/~$/) != null);
      },
      persistent: true,
      interval: 511
    };
    dirs = ['pages', 'src', 'static', 'scss'];
    for (_i = 0, _len = dirs.length; _i < _len; _i++) {
      dir = dirs[_i];
      watch.watchTree(dir, opts, fileChangeCallback);
    }
    fs.watchFile('layout.html.coffee', opts, lazyBuild);
    console.log('watching for changes...');
    return typeof callback === "function" ? callback() : void 0;
  };

}).call(this);
