// Generated by IcedCoffeeScript 1.3.3g
(function() {
  var default_index_content, default_layout_content, default_style_content, fs, fsextra, _ref;

  fs = require('fs');

  fsextra = require('fs.extra');

  _ref = [null, null, null], default_layout_content = _ref[0], default_index_content = _ref[1], default_style_content = _ref[2];

  module.exports = function() {
    console.log('Generating skeleton project...');
    try {
      fs.writeFile('layout.html.coffee', default_layout_content, function(err) {
        if (err) return console.error(err);
      });
      console.log('  layout.html.coffee'.green);
      console.log('\tThis is the layout template that every page will share.');
      fsextra.mkdirRecursiveSync('pages');
      fs.writeFile('pages/index.html.coffee', default_index_content, function(err) {
        if (err) return console.error(err);
      });
      console.log('  pages/'.green);
      console.log('\tThis is where coffeecup templates go (like index.html.coffee).');
      console.log('\tThey\'ll be compiled into *.html files in the release folder.');
      fsextra.mkdirRecursiveSync('scss');
      fs.writeFile('scss/style.scss', default_style_content, function(err) {
        if (err) return console.error(err);
      });
      console.log('  scss/'.green);
      console.log('\tThis is where the SCSS source files go.');
      console.log('\tThey\'ll be compiled into css/*.css files in the release folder.');
      fsextra.mkdirRecursiveSync('src');
      console.log('  src/'.green);
      console.log('\tThis is where all your coffeescript source files will go.');
      console.log('\tThey\'ll be compiled into lib/*.js files in the release folder.');
      fsextra.mkdirRecursiveSync('static');
      console.log('  static/'.green);
      return console.log('\tThis is where all your static resources (images, etc) go.');
    } catch (e) {
      return console.error(e);
    }
  };

  default_layout_content = "doctype 5\nhtml class: 'no-js', ->\n  head ->\n    meta charset: 'utf-8'\n    meta 'http-equiv': 'X-UA-Compatible', content: 'IE=edge,chrome=1'\n    title ''\n    link rel: 'stylesheet', href: '/css/style.css'\n  body ->\n    ie 'IE7', ->\n      p '.chromeframe', 'You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browswer</a> or <a href=\"http://www.google.com/chromeframe/?redirect=true\">activate Google Chrome Frame</a> to improve your experience.'\n    div -> @body\n";

  default_index_content = "body = ->\n  p 'Welcome to Starman'\n";

  default_style_content = "body {\n  font-size: 1em;\n  line-height: 1.4;\n}\n";

}).call(this);
