// Generated by IcedCoffeeScript 1.3.3g
(function() {

  module.exports.init = function() {
    return console.log('init');
  };

  module.exports.build = function() {
    return console.log('build');
  };

  module.exports.watch = function() {
    return console.log('watch');
  };

  module.exports.serve = function() {
    return console.log('serve');
  };

}).call(this);
