// Generated by IcedCoffeeScript 1.3.3g
(function() {

  module.exports = function(callback) {
    console.log('todo: watch');
    return typeof callback === "function" ? callback() : void 0;
  };

}).call(this);
